version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewTestProjectProject
  gitServerName: shshiExternal
  gitUrl: https://github.com/Shilpa-Shivaji-IBM
  gitUsername: Shilpa-Shivaji-IBM
  gitBranch: main
services:
- serviceName: project.newtestproject.integrations:flow1
  packages:
  - name: NewTestProjectProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2038
- serviceName: project.newtestproject.integrations:flow2
  packages:
  - name: NewTestProjectProject
    version: "1.0"
